-- TABLA 1 FAMILIA
/*CREATE TABLE FAMILIA (Codfamilia NUMBER(3) CONSTRAINT PK_CODFAMILIA PRIMARY KEY,
Denofamilia VARCHAR2(50) CONSTRAINT NN_DENOFAMILIA NOT NULL,
CONSTRAINT UNIQUE_FAMILIA UNIQUE(Denofamilia));*/

-- TABLA 2 PRODUCTO 
CREATE TABLE PRODUCTO(Codproducto NUMBER(5) CONSTRAINT PK_PRODUCTO PRIMARY KEY,
Denoproducto VARCHAR2(50) CONSTRAINT NN_DENOPRODUCTO NOT NULL,
Descripcion VARCHAR2(100),
PrecioBase NUMBER (8,2) CONSTRAINT NN_PRECIOBASE NOT NULL,
CONSTRAINT PB_POSITIVO CHECK (PrecioBase > 0),
PorcReposición NUMBER(3) CONSTRAINT PORCREPO_POSITIVO CHECK (PorcReposición > 0),
UnidadesMinimas NUMBER(4)NOT NULL,
CONSTRAINT UDMIN_POSITIVO CHECK (UnidadesMinimas > 0),
Codfamilia NUMBER(3) CONSTRAINT NN_CODFAM NOT NULL,
CONSTRAINT FK_CLAVEAJFAMILIA FOREIGN KEY(Codfamilia) REFERENCES FAMILIA(Codfamilia));

/* 
CREATE TABLE TIENDA(Codtienda NUMBER(3) CONSTRAINT PK_TIENDA PRIMARY KEY,
Denotienda VARCHAR2(20) NOT NULL,
Telefono VARCHAR2(11),
CodigoPostal VARCHAR2(5) NOT NULL,
Provincia VARCHAR2(5) NOT NULL); */

-- TABLA 4 STOCK
CREATE TABLE STOCK(Codtienda NUMBER(3) NOT NULL,
CONSTRAINT FK_CLAVEAJTIENDA FOREIGN KEY(Codtienda) REFERENCES TIENDA(Codtienda),
Codproducto NUMBER(5) NOT NULL,
CONSTRAINT FK_CLAVEAJPRODUCTO FOREIGN KEY(Codproducto) REFERENCES PRODUCTO(Codproducto),
Unidades NUMBER(6) NOT NULL,
CONSTRAINT PK_STOCK PRIMARY KEY (Codtienda,Codproducto),
CONSTRAINT POSITIVO CHECK (Unidades >= 0));